### ISSUE TITLE
what can we do about this during the VIRUS?

### ISSUE THREAD

**Issue by gonzalezgarcia** [ortiztud/ecos#4]

**Comment by ortiztudela** [comment]
So, the question is whether we want to get this out and which are the steps needed to do it. I've looked at the draft again and I have renewed energies. I feel this can be appealing to people perhaps with a few more tweaks and perhaps one more round of datacollection. Are you still up for it?

**Comment by gonzalezgarcia** [comment]
I completely forgot that I opened this issue...
You are ~~a bit~~ a lot more familiar with this literature, so my question would be if you think this has some interest for people in the field?  I'm totally up for it. I might even be able eto put some money in my prolific account so we can test online...

**Comment by ortiztudela** [comment]
Thinking out loud here: 

I honestly think that the idea of having a database of pictures with semantic relatedness measures can be useful for a lot of experiments. 
Relatedness measures for words are easy to find out there and had been extensively used. One could potentially select pictures "representing" certain words from those databases and infer that whatever measure was obtained for words should also apply for the pictures. However, we have already seen in this very project that is not as straightforward since the 1:1 correspondance between images and words is not always granted (see the jackal example in our dataset).

SCEGRAM (https://link.springer.com/article/10.3758/s13428-016-0820-3) is a database with a similar underlying principle but for composed scenes. ECOS is more suitable for paradigms aiming at using scene-to-object or object-to-scene relations (outside of the scene processing field) with individual stimuli (which is great for counterbalancing... *and we all love counterbalancing*).
